name: Discord Notification

on:
  issues:
    types:
      - opened

  pull_request:
    types:
      - opened
      - review_requested
      - closed

jobs:
  discord:
    uses: MAC-MakeAnimationChart/.github/.github/workflows/discord-notify.yml@main
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
